name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create Android project files
        run: flutter create . --platforms=android

      - name: Change package name
        run: flutter pub run change_app_package_name:main com.apptools.systemsuite

      - name: Add permissions to AndroidManifest
        run: |
          sed -i '/<\/application>/i \    <queries>\n        <intent>\n            <action android:name="android.intent.action.MAIN" \/>\n        <\/intent>\n    <\/queries>' android/app/src/main/AndroidManifest.xml

      - name: Change app display name
        run: sed -i 's/android:label="system_suite"/android:label="System Suite"/g' android/app/src/main/AndroidManifest.xml

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/*.apk
